services:
  postgres:
    image: postgres:15-alpine
    container_name: parcial3_postgres
    environment:
      POSTGRES_DB: parcial3_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parcial3_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: parcial3_app
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parcial3_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parcial3_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  parcial3_network:
    driver: bridge